
import React from 'react';
import { BookOpen, Calculator, Atom, Globe, Book, GraduationCap, Heart, Languages, Brain, Activity, Scroll } from 'lucide-react';
import { UserRole, Subject, User, AcademicItem, Language } from './types';

export const APP_NAME = "1BacSMF-2";

// Valid UUID for the Bot User to satisfy database constraints
export const ZAY_USER_ID = '00000000-0000-0000-0000-000000000001';

export const INITIAL_SUBJECTS: Subject[] = [
  { 
    id: 'math', 
    name: { en: 'Mathematics SM', fr: 'Mathématiques SM', ar: 'الرياضيات م.ر' }, 
    description: { en: 'Logic, Sets, Functions', fr: 'Logique, Ensembles, Fonctions', ar: 'المنطق، المجموعات، الدوال' }, 
    color: 'bg-blue-600',
    coefficient: 7
  },
  { 
    id: 'physics', 
    name: { en: 'Physics & Chemistry', fr: 'Physique-Chimie', ar: 'الفيزياء والكيمياء' }, 
    description: { en: 'Mechanics & Redox', fr: 'Mécanique & Redox', ar: 'الميكانيكا والكيمياء' }, 
    color: 'bg-purple-600',
    coefficient: 7
  },
  { 
    id: 'svt', 
    name: { en: 'SVT', fr: 'SVT', ar: 'علوم الحياة والأرض' }, 
    description: { en: 'Geology & Biology', fr: 'Géologie & Biologie', ar: 'الجيولوجيا والبيولوجيا' }, 
    color: 'bg-green-600',
    coefficient: 2
  },
  { 
    id: 'fr', 
    name: { en: 'French', fr: 'Français', ar: 'اللغة الفرنسية' }, 
    description: { en: 'The Antigone, Le Dernier Jour', fr: 'Antigone, Le Dernier Jour', ar: 'الأدب الفرنسي' }, 
    color: 'bg-red-600',
    coefficient: 4
  },
  { 
    id: 'ar', 
    name: { en: 'Arabic', fr: 'Arabe', ar: 'اللغة العربية' }, 
    description: { en: 'Literature', fr: 'Littérature', ar: 'الأدب العربي' }, 
    color: 'bg-emerald-600',
    coefficient: 2
  },
  { 
    id: 'islamic', 
    name: { en: 'Islamic Education', fr: 'Éducation Islamique', ar: 'التربية الإسلامية' }, 
    description: { en: 'Faith and Values', fr: 'Foi et Valeurs', ar: 'العقيدة والقيم' }, 
    color: 'bg-teal-600',
    coefficient: 2
  },
  { 
    id: 'history', 
    name: { en: 'History & Geography', fr: 'Histoire-Géo', ar: 'التاريخ والجغرافيا' }, 
    description: { en: 'World History & Maps', fr: 'Histoire Mondiale & Cartes', ar: 'التاريخ العالمي والجغرافيا' }, 
    color: 'bg-yellow-600',
    coefficient: 2
  },
  { 
    id: 'english', 
    name: { en: 'English', fr: 'Anglais', ar: 'اللغة الإنجليزية' }, 
    description: { en: 'Grammar and Vocab', fr: 'Grammaire et Vocabulaire', ar: 'اللغة الإنجليزية' }, 
    color: 'bg-indigo-600',
    coefficient: 2
  },
  { 
    id: 'phil', 
    name: { en: 'Philosophy', fr: 'Philosophie', ar: 'الفلسفة' }, 
    description: { en: 'Reason and Truth', fr: 'Raison et Vérité', ar: 'المجزوءات الفلسفية' }, 
    color: 'bg-amber-600',
    coefficient: 2
  },
  { 
    id: 'eps', 
    name: { en: 'Sports', fr: 'E.P.S', ar: 'التربية البدنية' }, 
    description: { en: 'Physical Activity', fr: 'Activité Physique', ar: 'الرياضة' }, 
    color: 'bg-orange-600',
    coefficient: 2
  }
];

export const MOCK_ITEMS: AcademicItem[] = [];

export const SUBJECT_ICONS: Record<string, React.ReactNode> = {
  math: <Calculator className="w-6 h-6" />,
  physics: <Atom className="w-6 h-6" />,
  svt: <Globe className="w-6 h-6" />,
  history: <Scroll className="w-6 h-6" />,
  ar: <Book className="w-6 h-6" />,
  fr: <BookOpen className="w-6 h-6" />,
  islamic: <Heart className="w-6 h-6" />,
  english: <Languages className="w-6 h-6" />,
  phil: <Brain className="w-6 h-6" />,
  eps: <Activity className="w-6 h-6" />,
};

export const TRANSLATIONS: Record<Language, any> = {
  en: {
    welcome: "Welcome",
    overview: "Home",
    calendar: "Exams & Events",
    subjects: "Curriculum",
    classlist: "Students",
    management: "Control Center",
    dev: "Dev Tools",
    credits: "Credits",
    chat: "Group Chat",
    logout: "Exit",
    login: "Login",
    register: "Join",
    email: "Email",
    password: "Password",
    name: "Full Name",
    secret: "Dev Key",
    studentId: "Student ID",
    exam: "Exam",
    homework: "Homework",
    event: "Event",
    task: "Task",
    due: "Deadline",
    add: "Create",
    save: "Save",
    delete: "Delete",
    edit: "Modify",
    cancel: "Cancel",
    notes: "Notes",
    resources: "Materials",
    today: "Today",
    no_items: "No tasks",
    time: "Time",
    room: "Room",
    location: "Location",
    placeholder_title: "Enter title...",
    placeholder_notes: "Add description...",
    upload_res: "Attach Resources",
    time_info: "Schedule Info",
    sim_avg: "Average",
    sim_goal: "Target Goal",
    sim_coeff: "Coeff",
    sim_exams: "Exams Count",
    sim_needed: "Needed for Target",
    chat_placeholder: "Type a message...",
    recording: "Recording...",
    release_send: "Release to Send",
    tap_record: "Tap mic to record",
    lesson_time: "Time Range",
    from: "From",
    to: "To",
    date: "Date",
    ai_metadata: "AI Metadata (Hidden)",
    logs: "AI Logs",
    upload_success: "File Uploaded Successfully",
    upload_fail: "Upload Failed",
    next_up: "Next Up (Scrollable)",
    agenda: "Agenda",
    week: "Week",
    month: "Month",
    all: "All",
    end_of_agenda: "End of Agenda",
    delete_confirm: "Are you sure you want to delete this?",
    search_tasks: "Search tasks...",
    tasks_homework: "Tasks & Homework",
    lessons_lib: "Lessons Library",
    ai_reports: "AI Reports",
    upload_new: "Add New Lesson / Summary",
    recent_uploads: "Recent Uploads",
    unresolved_failures: "Unresolved AI Failures",
    mark_done: "Mark as Done",
    all_resolved: "All AI requests satisfied.",
    no_results: "No results found",
    explore_curriculum: "Explore Curriculum",
    select_subject: "Select a subject to access materials",
    active_members: "active members",
    members_enrolled: "members enrolled",
    search_students: "Search students...",
    lesson_library: "Lesson Library",
    access_materials: "Access course materials, summaries, and exercises.",
    search_lessons: "Search lessons...",
    download_main: "Download Main File",
    edit_item: "Edit Item",
    new_item: "New Item",
    title: "Title",
    type: "Type",
    subject: "Subject",
    description: "Description",
    attachments: "Attachments",
    click_upload: "Click to upload files",
    files_pending: "files pending upload",
    exams_assessments: "Exams & Assessments",
    homework_exercises: "Homework & Exercises",
    no_exams: "No exams",
    clean_slate: "Clean slate",
    back_subjects: "Back to subjects",
    try_filter: "Try changing the filter or add a task",
    placeholder_room: "e.g. Salle 4",
    ac_status: "Academic Status: Active",
    curriculum_shortcut: "Curriculum Shortcut",
    upcoming_priority: "Upcoming Priority",
    all_clear: "All clear",
    in_hub: "in hub"
  },
  fr: {
    welcome: "Bienvenue",
    overview: "Accueil",
    calendar: "Calendrier",
    subjects: "Matières",
    classlist: "Étudiants",
    management: "Gestion",
    dev: "Console Dev",
    credits: "Crédits",
    chat: "Discussion",
    logout: "Sortie",
    login: "Connexion",
    register: "Inscription",
    email: "Email",
    password: "Mot de passe",
    name: "Nom Complet",
    secret: "Clé Dev",
    studentId: "ID Étudiant",
    exam: "Examen",
    homework: "Devoir",
    event: "Événement",
    task: "Tâche",
    due: "Échéance",
    add: "Ajouter",
    save: "Enregistrer",
    delete: "Supprimer",
    edit: "Modifier",
    cancel: "Annuler",
    notes: "Notes",
    resources: "Ressources",
    today: "Aujourd'hui",
    no_items: "Aucune tâche",
    time: "Heure",
    room: "Salle",
    location: "Lieu",
    placeholder_title: "Titre...",
    placeholder_notes: "Description...",
    upload_res: "Ajouter Ressources",
    time_info: "Horaire",
    sim_avg: "Moyenne",
    sim_goal: "Objectif",
    sim_coeff: "Coeff",
    sim_exams: "Nb Examens",
    sim_needed: "Note Requise",
    chat_placeholder: "Écrivez un message...",
    recording: "Enregistrement...",
    release_send: "Relâcher pour envoyer",
    tap_record: "Appuyez pour enregistrer",
    lesson_time: "Plage Horaire",
    from: "De",
    to: "À",
    date: "Date",
    ai_metadata: "Métadonnées IA (Caché)",
    logs: "Journaux IA",
    upload_success: "Fichier téléchargé",
    upload_fail: "Échec du téléchargement",
    next_up: "À Venir (Défiler)",
    agenda: "Agenda",
    week: "Semaine",
    month: "Mois",
    all: "Tout",
    end_of_agenda: "Fin de l'agenda",
    delete_confirm: "Êtes-vous sûr de vouloir supprimer ceci ?",
    search_tasks: "Rechercher des tâches...",
    tasks_homework: "Tâches et Devoirs",
    lessons_lib: "Bibliothèque de leçons",
    ai_reports: "Rapports IA",
    upload_new: "Ajouter une leçon / Résumé",
    recent_uploads: "Ajouts récents",
    unresolved_failures: "Échecs IA non résolus",
    mark_done: "Marquer comme fait",
    all_resolved: "Toutes les requêtes IA sont satisfaites.",
    no_results: "Aucun résultat trouvé",
    explore_curriculum: "Explorer le programme",
    select_subject: "Sélectionnez une matière pour accéder",
    active_members: "membres actifs",
    members_enrolled: "membres inscrits",
    search_students: "Rechercher des étudiants...",
    lesson_library: "Bibliothèque",
    access_materials: "Accédez aux cours, résumés et exercices.",
    search_lessons: "Rechercher des leçons...",
    download_main: "Télécharger le fichier",
    edit_item: "Modifier l'élément",
    new_item: "Nouvel élément",
    title: "Titre",
    type: "Type",
    subject: "Matière",
    description: "Description",
    attachments: "Pièces jointes",
    click_upload: "Cliquez pour télécharger",
    files_pending: "fichiers en attente",
    exams_assessments: "Examens et Évaluations",
    homework_exercises: "Devoirs et Exercices",
    no_exams: "Aucun examen",
    clean_slate: "Tout est propre",
    back_subjects: "Retour aux matières",
    try_filter: "Essayez de changer le filtre ou d'ajouter une tâche",
    placeholder_room: "ex. Salle 4",
    ac_status: "Statut Académique: Actif",
    curriculum_shortcut: "Raccourci Programme",
    upcoming_priority: "Priorité à venir",
    all_clear: "Tout est clair",
    in_hub: "dans le hub"
  },
  ar: {
    welcome: "مرحباً",
    overview: "الرئيسية",
    calendar: "الامتحانات",
    subjects: "المواد",
    classlist: "الطلاب",
    management: "التسيير",
    dev: "المطور",
    credits: "الاعتمادات",
    chat: "المحادثة",
    logout: "خروج",
    login: "دخول",
    register: "انضمام",
    email: "البريد",
    password: "كلمة السر",
    name: "الاسم الكامل",
    secret: "رمز المطور",
    studentId: "رقم الطالب",
    exam: "امتحان",
    homework: "واجب",
    event: "حدث",
    task: "مهمة",
    due: "الموعد",
    add: "إضافة",
    save: "حفظ",
    delete: "حذف",
    edit: "تعديل",
    cancel: "إلغاء",
    notes: "ملاحظات",
    resources: "موارد",
    today: "اليوم",
    no_items: "لا يوجد مهام",
    time: "الوقت",
    room: "القاعة",
    location: "المكان",
    placeholder_title: "العنوان...",
    placeholder_notes: "ملاحظات إضافية...",
    upload_res: "إرفاق موارد",
    time_info: "معلومات الوقت",
    sim_avg: "المعدل",
    sim_goal: "الهدف",
    sim_coeff: "المعامل",
    sim_exams: "عدد الفروض",
    sim_needed: "النقطة المطلوبة",
    chat_placeholder: "اكتب رسالة...",
    recording: "جاري التسجيل...",
    release_send: "اترك للإرسال",
    tap_record: "اضغط للتسجيل",
    lesson_time: "التوقيت",
    from: "من",
    to: "إلى",
    date: "التاريخ",
    ai_metadata: "بيانات الذكاء الاصطناعي",
    logs: "سجلات الذكاء الاصطناعي",
    upload_success: "تم الرفع بنجاح",
    upload_fail: "فشل الرفع",
    next_up: "القادم (تمرير)",
    agenda: "الأجندة",
    week: "أسبوع",
    month: "شهر",
    all: "الكل",
    end_of_agenda: "نهاية الجدول",
    delete_confirm: "هل أنت متأكد من الحذف؟",
    search_tasks: "بحث في المهام...",
    tasks_homework: "المهام والواجبات",
    lessons_lib: "مكتبة الدروس",
    ai_reports: "تقارير الذكاء الاصطناعي",
    upload_new: "إضافة درس / ملخص جديد",
    recent_uploads: "إضافات حديثة",
    unresolved_failures: "أخطاء الذكاء الاصطناعي",
    mark_done: "تحديد كمكتمل",
    all_resolved: "جميع طلبات الذكاء الاصطناعي محلولة.",
    no_results: "لا توجد نتائج",
    explore_curriculum: "استكشاف المقرر",
    select_subject: "اختر مادة للوصول للمحتوى",
    active_members: "أعضاء نشطين",
    members_enrolled: "أعضاء مسجلين",
    search_students: "بحث عن طلاب...",
    lesson_library: "المكتبة",
    access_materials: "الوصول إلى الدروس والملخصات والتمارين.",
    search_lessons: "بحث في الدروس...",
    download_main: "تحميل الملف الرئيسي",
    edit_item: "تعديل العنصر",
    new_item: "عنصر جديد",
    title: "العنوان",
    type: "النوع",
    subject: "المادة",
    description: "الوصف",
    attachments: "المرفقات",
    click_upload: "اضغط لرفع الملفات",
    files_pending: "ملفات قيد الانتظار",
    exams_assessments: "الامتحانات والتقييمات",
    homework_exercises: "الواجبات والتمارين",
    no_exams: "لا توجد امتحانات",
    clean_slate: "سجل نظيف",
    back_subjects: "العودة للمواد",
    try_filter: "جرب تغيير الفلتر أو أضف مهمة",
    placeholder_room: "مثال: القاعة 4",
    ac_status: "الحالة الدراسية: نشط",
    curriculum_shortcut: "اختصارات المقرر",
    upcoming_priority: "الأولويات القادمة",
    all_clear: "لا توجد مهام قادمة",
    in_hub: "في المنصة"
  }
};
